{
 "title": "Sock shop performance",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "route",
    "query": {
     "query": "label_values(request_duration_seconds_bucket, route)"
    }
   },
   {
    "name": "status",
    "query": "success : [2-3].*,error : [4-5].*"
   },
   {
    "name": "name",
    "query": "front-end : front-end, carts : carts, user : user, catalogue : catalogue, payment : payment, shipping : shipping, orders : orders"
   },
   { "name": "method", "query": "GET,POST,PUT,DELETE" }
  ]
 },
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket{name=\"$name\"}[1m])) by (name, le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_duration_seconds_bucket{name=\"$name\"}[1m])) by (name, le))",
     "legendFormat": "P50"
    },
    {
     "expr": "sum(rate(request_duration_seconds_sum{name=\"$name\"}[1m])) / sum(rate(request_duration_seconds_count{name=\"$name\"}[1m]))",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "round(\n    sum(\n        irate(\n            request_duration_seconds_sum\n            {\n                route!=\"$route\"\n, name=~\"$name\"            }[1m]\n            )\n        ) by (route), 0.001)",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_count{name=\"$name\",status_code=~\"2..\",route!=\"metrics\"}[1m])) * 100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(request_duration_seconds_count{name=\"$name\",status_code=~\"4.+|5.+\"}[1m])) * 100",
     "legendFormat": "4xx/5xx"
    }
   ]
  }
 ]
}