---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rabbitmq.rabbitmqLabel }}
  #namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.rabbitmq.rabbitmqLabel }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9090'
spec:
  ports:
    # the port that this service should serve on
  - port: 5672
    name: rabbitmq
    targetPort: 5672
  - port: 9090
    name: exporter
    targetPort: exporter
    protocol: TCP
  selector:
    name: {{ .Values.rabbitmq.rabbitmqLabel }}
