variable "region" {
  description = "AWS region"
  type = string
  default = "us-east-1"
}

variable "cluster_name" {
  description = "EKS cluster name"
  type = string
}

variable "vpc_cidr_block" {
  description = "VPC CIDR block"
  type = string
}

variable "private_subnet_blocks" {
  description = "cidr, availability zone for private subnets"
  type = map(object({
    cidr = string
    az = string
  }))
}

variable "public_subnet_blocks" {
  description = "cidr, availability zone for public subnets"
  type = map(object({
    cidr = string
    az = string
  }))
}

variable "intra_subnet_blocks" {
  description = "cidr, availability zone for intra subnets"
  type = map(object({
    cidr = string
    az = string
  }))
}

variable "instance_type" {
  description = "Instance type for the worker nodes"
  type = string
  default = "t3.large"
}

variable "cert_manager_sa" {
  description = "name of cert manager service account to override the default helm chart"
  type = string
  default = "cert-manager"
}

variable "domain" {
  description = "route53 domain name"
  type = string
}

variable "chartname" {
  description = "the release name to be given to the cert-manager helm chart"
  type = string
  default = "cert-manager"
}

variable "email" {
  description = "the email address to use for letsencrypt"
  type = string
}

variable "argocd-domain" {
  description = "subdomain name for argocd"
  type = string
}

variable "controller-full-name" {
  description = "this value overrides the nginx ingress controller fullname"
  type = string
  default = "nginx"
}

variable "controller-name" {
  description = "this value overrides the default nginx ingress controller name"
  type = string
  default = "controller"
}

variable "wildcard_secret_name" {
  description = "the name os the wildcard certificate generated by letsencrypt"
  type = string 
  default = "wildcard-cert"
}

variable "argoslack" {
  description = "slackbot for argocd notifications"
  type = string
}

variable "prometheusslack" {
  description = "slackbot for alert-manager notifications"
  type = string
}

variable "argocdpass" {
  description = "argocd password"
  type = string
}

variable "grafana_domain" {
  description = "sub domain name for grafana"
  type = string
}

variable "prom_domain" {
  description = "sub domain name for prometheus"
  type = string
}
