---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.catalogue.catalogueLabel }}
  labels:
    name: {{ .Values.catalogue.catalogueLabel }}
    #namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      name: {{ .Values.catalogue.catalogueLabel }}
  template:
    metadata:
      labels:
        name: {{ .Values.catalogue.catalogueLabel }}
    spec:
      containers:
      - name: {{ .Values.catalogue.catalogueLabel }}
        image: "{{ .Values.catalogue.image.repo }}:{{ .Values.catalogue.image.tag }}"
        command: ["/app"]
        args:
        - -port={{ .Values.catalogue.containerPort }}
        resources:
{{ toYaml .Values.catalogue.resources | indent 10 }}
        ports:
        - containerPort: {{ .Values.catalogue.containerPort }}
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.catalogue.containerPort }}
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.catalogue.containerPort }}
          initialDelaySeconds: 180
          periodSeconds: 3
