---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.rabbitmq.rabbitmqLabel }}
  #namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.rabbitmq.rabbitmqLabel }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      name: {{ .Values.rabbitmq.rabbitmqLabel }}
  template:
    metadata:
      labels:
        name: {{ .Values.rabbitmq.rabbitmqLabel }}
    spec:
      containers:
      - name: {{ .Values.rabbitmq.rabbitmqLabel }}
        image: "{{ .Values.rabbitmq.image.repo }}:{{ .Values.rabbitmq.image.tag }}"
        ports:
        - containerPort: 15672
          name: management
        - containerPort: 5672
        resources:
{{ toYaml .Values.rabbitmq.resources | indent 10 }}
        securityContext:
          capabilities:
            drop:
              - all
            add:
              - CHOWN
              - SETGID
              - SETUID
              - DAC_OVERRIDE
          readOnlyRootFilesystem: true
      - name: rabbitmq-exporter
        image: kbudde/rabbitmq-exporter
        ports:
        - containerPort: 9090
          name: exporter
