---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.user.userLabel }}
  #namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.user.userLabel }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      name: {{ .Values.user.userLabel }}
  template:
    metadata:
      labels:
        name: {{ .Values.user.userLabel }}
    spec:
      containers:
      - name: {{ .Values.user.userLabel }}
        image: "{{ .Values.user.image.repo }}:{{ .Values.user.image.tag }}"
        resources:
{{ toYaml .Values.user.resources | indent 10 }}
        ports:
        - containerPort: {{ .Values.user.containerPort }}
        env:
        - name: mongo
          value: user-db:27017
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          tcpSocket:
            port: {{ .Values.user.containerPort }}
          initialDelaySeconds: 180
          periodSeconds: 3
