name: Destroy EKS Infrastructure

on:
  workflow_dispatch:

jobs:
  infrastructure:
    env:  
 # Credentials for deployment to AWS
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
# Credentials to sign into argocd and the slack api url
      argoslack: ${{ secrets.TF_VAR_ARGOSLACK }}
      prometheusslack: ${{ secrets.TF_VAR_PROMETHEUSSLACK }}
      argocdpass: ${{ secrets.TF_VAR_ARGOCDPASS }}
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./infrastructure
        
    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v3
        
      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0
          
      - name: Install kubectl
        run: |
          cd ..
          sudo apt-get update &&
          sudo apt-get install -y ca-certificates curl &&
          sudo curl -fsSLo /etc/apt/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg &&
          echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list &&
          sudo apt-get update &&
          sudo apt-get install -y kubectl

      - name: Terraform init
        id: init
        run: terraform init 

      - name: Terraform state list
        id: state
        run: terraform state list