name: 'Terraform code to deploy the EKS infrastructure'

on:
  push:
    branches: 
      - main
  pull_request:
  
  
jobs:
  infrastructure:
    env:  
 # Credentials for deployment to AWS
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
# Credentials to sign into argocd and the slack api url
      argoslack: ${{ secrets.TF_VAR_ARGOSLACK }}
      prometheusslack: ${{ secrets.TF_VAR_PROMETHEUSSLACK }}
      argocdpass: ${{ secrets.TF_VAR_ARGOCDPASS }}
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./infrastructure
        
    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v3
        
      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0
          
      - name: Install kubectl
        run: |
          cd ..
          sudo apt-get update &&
          sudo apt-get install -y ca-certificates curl &&
          sudo curl -fsSLo /etc/apt/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg &&
          echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list &&
          sudo apt-get update &&
          sudo apt-get install -y kubectl

      - name: Terraform init
        id: init
        run: terraform init 
        
      - name: Terraform plan
        id: plan
        run: terraform plan -var="argocdpass=${{ secrets.TF_VAR_argocdpass }}" -var="argoslack=${{ secrets.TF_VAR_argoslack }}" -var="prometheusslack=${{ secrets.TF_VAR_prometheusslack }}" -input=false
      
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
      
      - name: Terraform apply
        id: apply
        run: terraform apply -var="argocdpass=${{ secrets.TF_VAR_argocdpass }}" -var="argoslack=${{ secrets.TF_VAR_argoslack }}" -var="prometheusslack=${{ secrets.TF_VAR_prometheusslack }}" -auto-approve -input=false
      
      - name: Archive loadbalancer hostname file
        uses: actions/upload-artifact@v3
        with:
          name: loadbalancer
          path: ./nlb_hostname.txt
   
        
