name: Cypress Tests
on:
  workflow_dispatch:
  repository_dispatch:
    types: [run-cypress-tests]

jobs:
  infrastructure:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
    - name: Install kubectl
      run: |
        sleep 300