name: Cypress Tests
on:
  schedule:
    # runs tests every day at 4am
    - cron: '0 4 * * *'
  workflow_dispatch:
  repository_dispatch:
    types: [run-cypress-tests]

jobs:
  infrastructure:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
    - name: Install kubectl
      run: |
        sleep 2100