name: Cypress Tests 
on:
  workflow_dispatch:
  repository_dispatch:
    types: [run-cypress-tests]

jobs:
  infrastructure:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
    - name: Log Unique ID ${{ github.event.client_payload.unique_id }}
      run: |
        echo ${{ github.event.client_payload.unique_id }}
    - name: Install kubectl
      run: |
        sleep 300